CREATE DATABASE IF NOT EXISTS email_sender;

USE email_sender;

CREATE TABLE IF NOT EXISTS emails  (
    id INT NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subject VARCHAR(100) NOT NULL,
    content VARCHAR(250) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;